name: at
version: '${project.version}'
main: alini.cn.at.At
softdepend: [LuckPerms, GroupManager]
commands:
  at:
    description: 试试在聊天中@别人吧
    usage: /<command> <enable|disable>
    children:
    enable:
      description: 启用@免打扰
      usage: /<command> enable
      disable:
        description: 禁用@免打扰
        usage: /<command> disable
      reload:
        description: 重载插件配置
        usage: /<command> reload
      shield:
        description: 开启某人的@消息免打扰
        usage: /<command> shield <player>
      unshield:
        description: 关闭某人的@消息免打扰
        usage: /<command> unshield <player>
permissions:
  at.admin:
    description: 管理员权限
    default: op
  at.user:
    description: 用户权限
    default: op
  at.shield:
    description: 屏蔽权限
    default: false
  at.all:
    description: at所有人权限
    default: op
